// api.js - Archivio prodotti (finta API)
export const productDatabase = [
    { id: 1, name: 'Latte Intero', price: 1.50, category: 'latticini' },
    { id: 2, name: 'Latte Parzialmente Scremato', price: 1.45, category: 'latticini' },
    { id: 3, name: 'Latte Scremato', price: 1.40, category: 'latticini' },
    { id: 4, name: 'Latte di Soia', price: 2.20, category: 'latticini' },
    { id: 5, name: 'Latte di Avena', price: 2.50, category: 'latticini' },
    { id: 6, name: 'Uova (6 pezzi)', price: 3.00, category: 'latticini' },
    { id: 7, name: 'Uova Bio (6 pezzi)', price: 4.20, category: 'latticini' },
    { id: 8, name: 'Yogurt Greco', price: 1.80, category: 'latticini' },
    { id: 9, name: 'Yogurt Naturale', price: 1.20, category: 'latticini' },
    { id: 10, name: 'Yogurt alla Frutta', price: 1.50, category: 'latticini' },
    { id: 11, name: 'Burro', price: 3.20, category: 'latticini' },
    { id: 12, name: 'Panna da Cucina', price: 1.80, category: 'latticini' },
    { id: 13, name: 'Ricotta', price: 2.40, category: 'latticini' },
    { id: 14, name: 'Mozzarella', price: 2.80, category: 'formaggi' },
    { id: 15, name: 'Parmigiano Reggiano', price: 8.90, category: 'formaggi' },
    { id: 16, name: 'Gorgonzola', price: 4.50, category: 'formaggi' },
    { id: 17, name: 'Pecorino Romano', price: 6.20, category: 'formaggi' },
    { id: 18, name: 'Fontina', price: 5.80, category: 'formaggi' },
    { id: 19, name: 'Taleggio', price: 4.90, category: 'formaggi' },
    { id: 20, name: 'Stracchino', price: 3.20, category: 'formaggi' },
    { id: 21, name: 'Provolone', price: 4.80, category: 'formaggi' },
    { id: 22, name: 'Pane Casereccio', price: 2.20, category: 'panetteria' },
    { id: 23, name: 'Pane Integrale', price: 2.50, category: 'panetteria' },
    { id: 24, name: 'Pane di Segale', price: 2.80, category: 'panetteria' },
    { id: 25, name: 'Focaccia', price: 3.50, category: 'panetteria' },
    { id: 26, name: 'Grissini', price: 1.80, category: 'panetteria' },
    { id: 27, name: 'Crackers', price: 2.20, category: 'panetteria' },
    { id: 28, name: 'Fette Biscottate', price: 1.90, category: 'panetteria' },
    { id: 29, name: 'Pasta Spaghetti', price: 1.10, category: 'pasta' },
    { id: 30, name: 'Pasta Penne', price: 1.15, category: 'pasta' },
    { id: 31, name: 'Pasta Fusilli', price: 1.20, category: 'pasta' },
    { id: 32, name: 'Pasta Integrale', price: 1.80, category: 'pasta' },
    { id: 33, name: 'Lasagne', price: 1.50, category: 'pasta' },
    { id: 34, name: 'Gnocchi', price: 2.20, category: 'pasta' },
    { id: 35, name: 'Riso Arborio', price: 2.50, category: 'cereali' },
    { id: 36, name: 'Riso Basmati', price: 3.20, category: 'cereali' },
    { id: 37, name: 'Riso Integrale', price: 2.80, category: 'cereali' },
    { id: 38, name: 'Quinoa', price: 4.50, category: 'cereali' },
    { id: 39, name: 'Avena', price: 2.20, category: 'cereali' },
    { id: 40, name: 'Orzo', price: 1.80, category: 'cereali' },
    { id: 41, name: 'Banane (1kg)', price: 2.30, category: 'frutta' },
    { id: 42, name: 'Mele (1kg)', price: 2.10, category: 'frutta' },
    { id: 43, name: 'Pere (1kg)', price: 2.80, category: 'frutta' },
    { id: 44, name: 'Arance (1kg)', price: 1.90, category: 'frutta' },
    { id: 45, name: 'Limoni (500g)', price: 1.50, category: 'frutta' },
    { id: 46, name: 'Kiwi (500g)', price: 2.20, category: 'frutta' },
    { id: 47, name: 'Fragole (500g)', price: 3.50, category: 'frutta' },
    { id: 48, name: 'Uva (500g)', price: 2.80, category: 'frutta' },
    { id: 49, name: 'Pesche (1kg)', price: 3.20, category: 'frutta' },
    { id: 50, name: 'Albicocche (500g)', price: 3.80, category: 'frutta' },
    { id: 51, name: 'Ananas', price: 2.50, category: 'frutta' },
    { id: 52, name: 'Melone', price: 3.20, category: 'frutta' },
    { id: 53, name: 'Anguria', price: 4.50, category: 'frutta' },
    { id: 54, name: 'Pomodori (500g)', price: 1.90, category: 'verdura' },
    { id: 55, name: 'Insalata', price: 1.20, category: 'verdura' },
    { id: 56, name: 'Spinaci (500g)', price: 2.20, category: 'verdura' },
    { id: 57, name: 'Carote (1kg)', price: 1.50, category: 'verdura' },
    { id: 58, name: 'Zucchine (500g)', price: 1.80, category: 'verdura' },
    { id: 59, name: 'Melanzane (500g)', price: 2.50, category: 'verdura' },
    { id: 60, name: 'Peperoni (500g)', price: 2.80, category: 'verdura' },
    { id: 61, name: 'Cipolle (1kg)', price: 1.20, category: 'verdura' },
    { id: 62, name: 'Aglio (200g)', price: 1.50, category: 'verdura' },
    { id: 63, name: 'Patate (1kg)', price: 1.80, category: 'verdura' },
    { id: 64, name: 'Broccoli (500g)', price: 2.20, category: 'verdura' },
    { id: 65, name: 'Cavolfiore (500g)', price: 2.50, category: 'verdura' },
    { id: 66, name: 'Cetrioli (500g)', price: 1.60, category: 'verdura' },
    { id: 67, name: 'Basilico', price: 1.20, category: 'verdura' },
    { id: 68, name: 'Prezzemolo', price: 0.80, category: 'verdura' },
    { id: 69, name: 'Pollo (1kg)', price: 8.50, category: 'carne' },
    { id: 70, name: 'Manzo (500g)', price: 12.50, category: 'carne' },
    { id: 71, name: 'Maiale (500g)', price: 9.80, category: 'carne' },
    { id: 72, name: 'Agnello (500g)', price: 15.20, category: 'carne' },
    { id: 73, name: 'Salsicce (500g)', price: 6.50, category: 'carne' },
    { id: 74, name: 'Hamburger (4 pezzi)', price: 5.80, category: 'carne' },
    { id: 75, name: 'Bistecca (500g)', price: 14.50, category: 'carne' },
    { id: 76, name: 'Salmone (500g)', price: 12.80, category: 'pesce' },
    { id: 77, name: 'Branzino (500g)', price: 10.50, category: 'pesce' },
    { id: 78, name: 'Orata (500g)', price: 9.80, category: 'pesce' },
    { id: 79, name: 'Gamberetti (300g)', price: 8.50, category: 'pesce' },
    { id: 80, name: 'Calamari (500g)', price: 7.20, category: 'pesce' },
    { id: 81, name: 'Baccalà (300g)', price: 6.80, category: 'pesce' },
    { id: 82, name: 'Prosciutto Cotto', price: 5.20, category: 'salumi' },
    { id: 83, name: 'Prosciutto Crudo', price: 8.50, category: 'salumi' },
    { id: 84, name: 'Salame', price: 6.80, category: 'salumi' },
    { id: 85, name: 'Mortadella', price: 4.50, category: 'salumi' },
    { id: 86, name: 'Bresaola', price: 9.20, category: 'salumi' },
    { id: 87, name: 'Speck', price: 7.80, category: 'salumi' },
    { id: 88, name: 'Passata di Pomodoro', price: 0.90, category: 'conserve' },
    { id: 89, name: 'Pomodori Pelati', price: 1.20, category: 'conserve' },
    { id: 90, name: 'Tonno in Scatola', price: 1.60, category: 'conserve' },
    { id: 91, name: 'Salmone in Scatola', price: 2.80, category: 'conserve' },
    { id: 92, name: 'Fagioli in Scatola', price: 1.20, category: 'conserve' },
    { id: 93, name: 'Ceci in Scatola', price: 1.15, category: 'conserve' },
    { id: 94, name: 'Lenticchie in Scatola', price: 1.30, category: 'conserve' },
    { id: 95, name: 'Mais in Scatola', price: 1.10, category: 'conserve' },
    { id: 96, name: 'Olive Verdi', price: 2.20, category: 'conserve' },
    { id: 97, name: 'Olive Nere', price: 2.50, category: 'conserve' },
    { id: 98, name: 'Olio Extravergine', price: 4.50, category: 'condimenti' },
    { id: 99, name: 'Aceto Balsamico', price: 3.20, category: 'condimenti' },
    { id: 100, name: 'Sale', price: 0.80, category: 'condimenti' },
    { id: 101, name: 'Pepe Nero', price: 2.50, category: 'condimenti' },
    { id: 102, name: 'Origano', price: 1.50, category: 'condimenti' },
    { id: 103, name: 'Rosmarino', price: 1.80, category: 'condimenti' },
    { id: 104, name: 'Salvia', price: 1.60, category: 'condimenti' },
    { id: 105, name: 'Paprika', price: 2.20, category: 'condimenti' },
    { id: 106, name: 'Curcuma', price: 2.80, category: 'condimenti' },
    { id: 107, name: 'Zenzero', price: 3.20, category: 'condimenti' },
    { id: 108, name: 'Caffè Macinato', price: 3.80, category: 'bevande' },
    { id: 109, name: 'Caffè in Grani', price: 4.50, category: 'bevande' },
    { id: 110, name: 'Tè Verde', price: 2.20, category: 'bevande' },
    { id: 111, name: 'Tè Nero', price: 2.00, category: 'bevande' },
    { id: 112, name: 'Acqua Minerale (6 bottiglie)', price: 2.00, category: 'bevande' },
    { id: 113, name: 'Acqua Frizzante (6 bottiglie)', price: 2.20, category: 'bevande' },
    { id: 114, name: "Succo d'Arancia", price: 2.50, category: 'bevande' },
    { id: 115, name: 'Succo di Mela', price: 2.30, category: 'bevande' },
    { id: 116, name: 'Coca Cola', price: 1.80, category: 'bevande' },
    { id: 117, name: 'Birra (6 bottiglie)', price: 4.50, category: 'bevande' },
    { id: 118, name: 'Vino Rosso', price: 6.80, category: 'bevande' },
    { id: 119, name: 'Vino Bianco', price: 6.50, category: 'bevande' },
    { id: 120, name: 'Biscotti', price: 2.40, category: 'dolci' },
    { id: 121, name: 'Cioccolato Fondente', price: 3.20, category: 'dolci' },
    { id: 122, name: 'Cioccolato al Latte', price: 2.80, category: 'dolci' },
    { id: 123, name: 'Nutella', price: 4.50, category: 'dolci' },
    { id: 124, name: 'Marmellata', price: 2.80, category: 'dolci' },
    { id: 125, name: 'Miele', price: 4.20, category: 'dolci' },
    { id: 126, name: 'Patatine', price: 1.80, category: 'snack' },
    { id: 127, name: 'Noccioline', price: 2.50, category: 'snack' },
    { id: 128, name: 'Mandorle', price: 4.80, category: 'snack' },
    { id: 129, name: 'Pistacchi', price: 6.20, category: 'snack' },
    { id: 130, name: 'Gelato', price: 4.20, category: 'surgelati' },
    { id: 131, name: 'Pizza Surgelata', price: 3.50, category: 'surgelati' },
    { id: 132, name: 'Verdure Miste Surgelate', price: 2.80, category: 'surgelati' },
    { id: 133, name: 'Pesce Surgelato', price: 6.50, category: 'surgelati' },
    { id: 134, name: 'Patatine Surgelate', price: 2.20, category: 'surgelati' },
    { id: 135, name: 'Detersivo Piatti', price: 2.50, category: 'casa' },
    { id: 136, name: 'Detersivo Lavatrice', price: 4.80, category: 'casa' },
    { id: 137, name: 'Carta Igienica (8 rotoli)', price: 3.20, category: 'casa' },
    { id: 138, name: 'Tovaglioli', price: 1.50, category: 'casa' },
    { id: 139, name: 'Spugne', price: 2.20, category: 'casa' },
    { id: 140, name: 'Sacchetti Spazzatura', price: 2.80, category: 'casa' }
];